name: learn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  intl: ^0.19.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  syncfusion_flutter_charts: ^24.2.9
  firebase_auth: 4.17.8
  cloud_firestore: ^4.15.8
  rive: ^0.13.1
  shared_preferences: ^2.0.8
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.0
  percent_indicator: ^4.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # Icons Images
  - ./assets/images/appIcons/icon-steak.png
  - ./assets/images/appIcons/check-circle.png
  - ./assets/images/mascote/icon-loja-default.png
  - ./assets/images/mascote/icon-atividades-default.png
  - ./assets/images/mascote/icon-roupas-default.png
  - ./assets/images/mascote/icon-alimentos-default.png
  - ./assets/images/appIcons/icon-atividades-default.png
  - ./assets/images/appIcons/icon-atividades-select.png
  - ./assets/images/appIcons/icon-home-default.png
  - ./assets/images/appIcons/icon-home-select.png
  - ./assets/images/appIcons/icon-mascote-default.png
  - ./assets/images/appIcons/icon-mascote-select.png
  - ./assets/images/appIcons/icon-monitorar-default.png
  - ./assets/images/appIcons/icon-monitorar-select.png
  - ./assets/images/appIcons/icon-perfil-default.png
  - ./assets/images/appIcons/icon-perfil-select.png
  - ./assets/images/appIcons/progressFieldWithStars.png
  - ./assets/images/appIcons/progressFieldWithStarsBlue.png
  - ./assets/images/appIcons/icon-trophie.png
  - ./assets/images/appIcons/icon-award.png
  - ./assets/images/appIcons/icon-lock-default.png
  - ./assets/images/appIcons/notification.png
  - ./assets/images/appIcons/icon-show-conquist.png
  - ./assets/images/appIcons/activityIcon1.png
  - ./assets/images/appIcons/activityIcon2.png
  - ./assets/images/appIcons/activityIcon3.png
  - ./assets/images/appIcons/activityIcon4.png
  - ./assets/images/appIcons/backArrow.png
  - ./assets/images/appIcons/password_eye.png
  - ./assets/images/appIcons/password_eye_off.png
  - ./assets/images/appIcons/date_calendar.png
  - ./assets/images/appIcons/right_arrow.png
  - ./assets/images/appIcons/log-out.png
  - ./assets/images/appIcons/settings.png
  - ./assets/images/appIcons/bell.png
  - ./assets/images/appIcons/heart.png
  - ./assets/images/appIcons/left-arrow.png
  - ./assets/images/appIcons/camera.png
    - ./assets/images/appIcons/marked_checkbox.png
  - ./assets/images/appIcons/unmarked_checkbox.png
  - ./assets/images/appIcons/popup_slider.png
  - ./assets/images/appIcons/top.png
    - ./assets/images/appIcons/ranking.png


  # Badges
  - ./assets/images/appIcons/badge-bronze-default.png
  - ./assets/images/appIcons/badge-bronze-blue.png
  - ./assets/images/appIcons/badge-prata-default.png
  - ./assets/images/appIcons/badge-prata-blue.png
  - ./assets/images/appIcons/badge-ouro-default.png
  - ./assets/images/appIcons/badge-ouro-blue.png
  - ./assets/images/appIcons/badge-diamante-default.png
  - ./assets/images/appIcons/badge-diamante-blue.png
  - ./assets/images/appIcons/silver-badge.png
  - ./assets/images/levels/badge-bronze.png
  - ./assets/images/levels/badge-prata.png
  - ./assets/images/levels/badge-ouro.png
  - ./assets/images/levels/badge-diamante.png
  - ./assets/images/levels/bronze.png
  - ./assets/images/levels/prata.png
  - ./assets/images/levels/ouro.png
  - ./assets/images/levels/diamante.png
  
  # Person Images
  - ./assets/images/appImages/ianzinho.jpg
  - ./assets/images/appImages/joana-dias.png
  - ./assets/images/appImages/luciano.png
  - ./assets/images/appImages/activitiesBar.png
  - ./assets/images/appImages/AppIconBalloon.png
  - ./assets/images/appImages/carlos-dias.png

  # Mascot Images
  - ./assets/images/mascote/background.png
  - ./assets/images/mascote/backgroundLarge.png
  - ./assets/images/mascote/mascot-happy.png
  - ./assets/images/mascote/mascot-sad.png
  - ./assets/images/mascote/mascote.png

  # App Images
  - ./assets/images/appImages/icon.png
  - ./assets/images/appImages/correctBalloon.png
  - ./assets/images/appImages/wrongBalloon.png

  # Conquistas
  - ./assets/images/conquistas/conquista-1.png
  - ./assets/images/conquistas/conquista-2.png
  - ./assets/images/conquistas/conquista-3.png
  - ./assets/images/conquistas/conquista-4.png
  - ./assets/images/conquistas/conquista-5.png
  - ./assets/images/conquistas/conquista-6.png
  - ./assets/images/conquistas/new-conquist.png

  # Ballons
  - ./assets/images/ballons/pg3-a1.png
  - ./assets/images/ballons/pg3-a2.png
  - ./assets/images/ballons/pg3-a3.png
  - ./assets/images/ballons/pg5-a1.png
  - ./assets/images/ballons/pg5-a2.png
  - ./assets/images/ballons/pg5-a3.png
  - ./assets/images/ballons/pg7-a1.png
  - ./assets/images/ballons/pg7-a2.png
  - ./assets/images/ballons/pg7-a3.png
  - ./assets/images/ballons/pg9-a1.png
  - ./assets/images/ballons/pg9-a2.png
  - ./assets/images/ballons/pg9-a3.png
  - ./assets/images/ballons/pg11-a1.png
  - ./assets/images/ballons/pg11-a2.png
  - ./assets/images/ballons/pg11-a3.png
  - ./assets/images/ballons/pg13-a1.png
  - ./assets/images/ballons/pg13-a2.png
  - ./assets/images/ballons/pg13-a3.png

  # Animations
  - ./assets/animations/coinny.riv

  # GIFS
  - ./assets/gifs/loading_coins.gif
  - ./assets/gifs/loading_joystick.gif
  - ./assets/gifs/login_glasses.gif
  - ./assets/gifs/login_pig.gif
  - ./assets/gifs/confetti.gif

  # Profiles
  - ./assets/images/profiles/ball.png
  - ./assets/images/profiles/bear.png
  - ./assets/images/profiles/cube.png
  - ./assets/images/profiles/default.png
  - ./assets/images/profiles/game.png
  - ./assets/images/profiles/robot.png
  - ./assets/images/profiles/unicorn.png

  # Axctivities Images
  - ./assets/images/activities/como.png
  - ./assets/images/activities/metas.png
  - ./assets/images/activities/nece.png
  - ./assets/images/activities/planejar.png
  - ./assets/images/activities/poup.png
  - ./assets/images/activities/visao.png

  fonts:
    - family: Fieldwork-Geo
      fonts:
        - asset: assets/fonts/Fieldwork/Fieldwork10GeoRegular.otf
          weight: 400
        - asset: assets/fonts/Fieldwork/Fieldwork13SemiBoldGeo.otf
          weight: 600
        - asset: assets/fonts/Fieldwork/Fieldwork16GeoBold.otf
          weight: 700
        - asset: assets/fonts/Fieldwork/Fieldwork19GeoBlack.otf
          weight: 900
        - asset: assets/fonts/Fieldwork/Fieldwork1GeoHair.otf
          weight: 100
        - asset: assets/fonts/Fieldwork/Fieldwork22GeoFat.otf
          weight: 800
        - asset: assets/fonts/Fieldwork/Fieldwork4GeoThin.otf
          weight: 200
        - asset: assets/fonts/Fieldwork/Fieldwork7GeoLight.otf
          weight: 300

    - family: Fieldwork-Hum
      fonts:
        - asset: assets/fonts/Fieldwork/Fieldwork11HumRegular.otf
          weight: 400
        - asset: assets/fonts/Fieldwork/Fieldwork14HumDemiBold.otf
          weight: 600
        - asset: assets/fonts/Fieldwork/Fieldwork17HumBold.otf
          weight: 700
        - asset: assets/fonts/Fieldwork/Fieldwork20HumBlack.otf
          weight: 900
        - asset: assets/fonts/Fieldwork/Fieldwork23HumFat.otf
          weight: 800
        - asset: assets/fonts/Fieldwork/Fieldwork2HumHair.otf
          weight: 100
        - asset: assets/fonts/Fieldwork/Fieldwork5HumThin.otf
          weight: 200
        - asset: assets/fonts/Fieldwork/Fieldwork8HumLight.otf
          weight: 300

    - family: Spartan
      fonts:
        - asset: assets/fonts/Spartan/Spartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spartan/Spartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/Spartan/Spartan-Black.ttf
          weight: 900
        - asset: assets/fonts/Spartan/Spartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Spartan/Spartan-Thin.ttf
          weight: 100
        - asset: assets/fonts/Spartan/Spartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Spartan/Spartan-Light.ttf
          weight: 300
        - asset: assets/fonts/Spartan/Spartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/Spartan/Spartan-SemiBold.ttf
          weight: 600

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
